### ISSUE TITLE
in a case of invalid key, the node crashes the node-red instance

### ISSUE THREAD

**Issue by jmikerq** [diegopamio/node-red-contrib-ifttt#11]
In a case where an empty key is supplied, the node crashes Node-RED@0.17.5 instance.

The response from ifttt is: { errors: [ { message: 'You sent an invalid key.' } ] }

The error message is:

30 Oct 12:34:55 - SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
    at Request._callback (/home/mqiu/dev/test-node-red/node_modules/node-red/node_modules/node-red-contrib-ifttt/nodes/ifttt.js:35:27)
    at Request.self.callback (/home/mqiu/dev/test-node-red/node_modules/node-red/node_modules/node-red-contrib-ifttt/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/mqiu/dev/test-node-red/node_modules/node-red/node_modules/node-red-contrib-ifttt/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/mqiu/dev/test-node-red/node_modules/node-red/node_modules/node-red-contrib-ifttt/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by lorenwest** [comment]
Yes this could use better error handling around the JSON.parse. Pull requests accepted.

**Comment by lorenwest** [comment]
Merged fix and published at v0.1.0
