### ISSUE TITLE
node-red-contrib-ifttt crashed the whole Node-Red instance when internet is down

### ISSUE THREAD

**Issue by ndupont-net** [diegopamio/node-red-contrib-ifttt#19]
```
26 Feb 10:07:08 - [red] Uncaught Exception:
26 Feb 10:07:08 - TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Request._callback (/home/pi/.node-red/node_modules/node-red-contrib-ifttt/nodes/ifttt.js:37:34)
    at self.callback (/home/pi/.node-red/node_modules/node-red-contrib-ifttt/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/pi/.node-red/node_modules/node-red-contrib-ifttt/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
26 Feb 10:07:25 - [info]
Welcome to Node-RED
===================
26 Feb 10:07:25 - [info] Node-RED version: v0.19.4
26 Feb 10:07:25 - [info] Node.js  version: v8.11.1
26 Feb 10:07:25 - [info] Linux 4.14.79+ arm LE

```

Solved by replacing the error message in ifttt.js, line 37 by a no-brainer string containing a generic error message

**Comment by lorenwest** [comment]
Oh, man - I misread this as **node-red-contrib-ifttt crashes whole internet** and got chills...

The fix is in and the new version 0.2.1 is up on github and published to NPM.

Thank you for detecting and reporting this.
